# values.yaml
prometheus:
  service:
    type: NodePort
  prometheusSpec:
    podMonitorSelector:
      matchExpressions:
        - key: release
          operator: In
          values: ["monitoring"]
        - key: cnpg.io/cluster
          operator: Exists

grafana:
  service:
    type: NodePort

alertmanager:
  service:
    type: NodePort
