---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/cloudnative-pg/cloudnative-pg
  ref:
    tag: v1.27.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: cloudnative-pg
  path: ./releases/cnpg-1.27.0
  prune: true
  wait: true
  timeout: 5m