---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - cloudnative-pg-operator.yaml
  - cnpg-operator-config.yaml
  - headlamp-helm-repo.yaml
  - metrics-server-helm-repo.yaml
  - kube-prometheus-stack-operator.yaml