---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp-system
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: management-platform
    app.kubernetes.io/managed-by: Flux